let allData = null;

document.addEventListener('DOMContentLoaded', init);

document.getElementById('newListBtn').addEventListener('click', createNewList);
document.getElementById('deleteListBtn').addEventListener('click', deleteCurrentList);
document.getElementById('downloadBtn').addEventListener('click', downloadList);
document.getElementById('clearBtn').addEventListener('click', clearList);
document.getElementById('listSelector').addEventListener('change', switchList);

function init() {
    chrome.storage.local.get(['dimData'], (result) => {
        if (!result.dimData) {
            allData = { activeId: 'default', lists: { 'default': { name: 'Main Wishlist', items: {} } } };
            saveData();
        } else {
            allData = result.dimData;
            renderUI();
        }
    });
}

function renderUI() {
    const selector = document.getElementById('listSelector');
    const container = document.getElementById('weaponList');
    
    selector.innerHTML = '';
    Object.keys(allData.lists).forEach(listId => {
        const option = document.createElement('option');
        option.value = listId;
        option.text = allData.lists[listId].name;
        if (listId === allData.activeId) option.selected = true;
        selector.appendChild(option);
    });

    container.innerHTML = '';
    const activeList = allData.lists[allData.activeId];
    const weapons = Object.values(activeList.items || {}).sort((a, b) => a.name.localeCompare(b.name));

    if (weapons.length === 0) {
        container.innerHTML = '<div style="padding:10px; text-align:center;">List is empty.</div>';
        return;
    }

    weapons.forEach(weapon => {
        const details = document.createElement('details');
        const summary = document.createElement('summary');
        summary.textContent = `${weapon.name} (${weapon.rolls.length})`;
        details.appendChild(summary);

        weapon.rolls.forEach((roll, index) => {
            const row = document.createElement('div');
            row.className = 'roll-row';
            const displayText = roll.date ? `${roll.date}` : `Roll #${index + 1}`;
            
            row.innerHTML = `
                <span style="font-family:monospace; color:#888;">${displayText}</span>
                <button class="btn-del" title="Delete">×</button>
            `;
            row.querySelector('.btn-del').addEventListener('click', () => deleteRoll(weapon.hash, index));
            details.appendChild(row);
        });
        container.appendChild(details);
    });
}

function createNewList() {
    const name = prompt("New List Name:");
    if (name) {
        const id = 'list_' + Date.now();
        allData.lists[id] = { name: name, items: {} };
        allData.activeId = id;
        saveData();
    }
}

function deleteCurrentList() {
    if (Object.keys(allData.lists).length <= 1) return alert("Cannot delete only list.");
    if (confirm("Delete this list?")) {
        delete allData.lists[allData.activeId];
        allData.activeId = Object.keys(allData.lists)[0];
        saveData();
    }
}

function switchList(e) {
    allData.activeId = e.target.value;
    saveData();
    renderUI();
}

function deleteRoll(hash, index) {
    const list = allData.lists[allData.activeId];
    list.items[hash].rolls.splice(index, 1);
    if (list.items[hash].rolls.length === 0) delete list.items[hash];
    saveData();
}

function clearList() {
    if (confirm("Clear all?")) {
        allData.lists[allData.activeId].items = {};
        saveData();
    }
}

function downloadList() {
    const list = allData.lists[allData.activeId];
    let content = `title: ${list.name}\ndescription: Generated by DIM Extension\n\n`;
    Object.values(list.items || {}).forEach(w => {
        content += `// ${w.name}\n`;
        w.rolls.forEach(r => content += `${r.raw}\n`);
        content += `\n`;
    });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([content], {type: 'text/plain'}));
    a.download = `${list.name}.txt`;
    a.click();
}

function saveData() {
    chrome.storage.local.set({ dimData: allData }, renderUI);
}