// State
let allData = null;

document.addEventListener('DOMContentLoaded', init);

// Event Listeners
document.getElementById('newListBtn').addEventListener('click', createNewList);
document.getElementById('deleteListBtn').addEventListener('click', deleteCurrentList); // <--- NEW LISTENER
document.getElementById('downloadBtn').addEventListener('click', downloadList);
document.getElementById('clearBtn').addEventListener('click', clearList);
document.getElementById('listSelector').addEventListener('change', switchList);

// 1. Initialization
function init() {
    chrome.storage.local.get(['dimData'], (result) => {
        if (!result.dimData) {
            allData = { activeId: 'default', lists: { 'default': { name: 'Main Wishlist', items: {} } } };
            saveData();
        } else {
            allData = result.dimData;
            renderUI();
        }
    });
}

// 2. Render the Interface
function renderUI() {
    const selector = document.getElementById('listSelector');
    const container = document.getElementById('weaponList');
    
    // A. Populate Dropdown
    selector.innerHTML = '';
    Object.keys(allData.lists).forEach(listId => {
        const option = document.createElement('option');
        option.value = listId;
        option.text = allData.lists[listId].name;
        if (listId === allData.activeId) option.selected = true;
        selector.appendChild(option);
    });

    // B. Populate Weapon List
    container.innerHTML = '';
    const activeList = allData.lists[allData.activeId];
    
    const weapons = Object.values(activeList.items || {}).sort((a, b) => a.name.localeCompare(b.name));

    if (weapons.length === 0) {
        container.innerHTML = '<div style="padding:10px; text-align:center;">List is empty.</div>';
        return;
    }

    weapons.forEach(weapon => {
        const details = document.createElement('details');
        
        const summary = document.createElement('summary');
        summary.textContent = `${weapon.name} (${weapon.rolls.length})`;
        details.appendChild(summary);

        weapon.rolls.forEach((roll, index) => {
            const row = document.createElement('div');
            row.className = 'roll-row';
            const displayText = roll.date ? `Saved: ${roll.date}` : `Roll #${index + 1}`;
            
            row.innerHTML = `
                <span class="roll-info">${displayText}</span>
                <button class="btn-del" title="Delete Roll">×</button>
            `;

            row.querySelector('.btn-del').addEventListener('click', () => {
                deleteRoll(weapon.hash, index);
            });

            details.appendChild(row);
        });

        container.appendChild(details);
    });
}

// 3. Logic Functions

function createNewList() {
    const name = prompt("New List Name:");
    if (name) {
        const id = 'list_' + Date.now();
        allData.lists[id] = { name: name, items: {} };
        allData.activeId = id;
        saveData();
    }
}

// NEW: Delete the entire list
function deleteCurrentList() {
    const listIds = Object.keys(allData.lists);
    
    // Prevent deleting the last list
    if (listIds.length <= 1) {
        alert("You cannot delete the only list you have.");
        return;
    }

    const currentListName = allData.lists[allData.activeId].name;
    
    if (confirm(`Are you sure you want to permanently delete "${currentListName}"?`)) {
        // Remove the list
        delete allData.lists[allData.activeId];
        
        // Switch to the first available list remaining
        allData.activeId = Object.keys(allData.lists)[0];
        
        saveData();
    }
}

function switchList(e) {
    allData.activeId = e.target.value;
    saveData(); // Save selection so it remembers next time
    renderUI();
}

function deleteRoll(itemHash, rollIndex) {
    const activeList = allData.lists[allData.activeId];
    const weapon = activeList.items[itemHash];
    
    weapon.rolls.splice(rollIndex, 1);
    
    if (weapon.rolls.length === 0) {
        delete activeList.items[itemHash];
    }
    
    saveData();
}

function clearList() {
    if (confirm("Delete all items in this list?")) {
        allData.lists[allData.activeId].items = {};
        saveData();
    }
}

function downloadList() {
    const activeList = allData.lists[allData.activeId];
    const weapons = Object.values(activeList.items || {});
    
    if (weapons.length === 0) return alert("Nothing to download.");

    let content = `title: ${activeList.name}\ndescription: Generated by DIM Extension\n\n`;

    weapons.forEach(weapon => {
        content += `// ${weapon.name}\n`;
        weapon.rolls.forEach(roll => {
            content += `${roll.raw}\n`;
        });
        content += `\n`;
    });

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeList.name}.txt`;
    a.click();
}

function saveData() {
    chrome.storage.local.set({ dimData: allData }, renderUI);
}